// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/3/2026, 18:17:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/plugins/**/*.{js,ts,mjs}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/composables/**/*.{js,ts,mjs}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/utils/**/*.{js,ts,mjs}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/carlo/Desktop/lemoncode-master/modulo-05-metaframeworks/nuxt-rental/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;